### ISSUE TITLE
Feature #1: User can create a recipe

### ISSUE THREAD

**Issue by TheDanYount** [TheDanYount/my-cookbook#1]
## ⚙️ Feature
User can create a new recipe
## 📐 Functionality
1. On the TableofContents page of a cookbook, users will be able to click a button that allows them to create a new recipe.
## ✅ Task List
- [x] Update db to fix typo and include length and order for recipes
- [x] Insert dummy data for user and cookbook
- [x] Add tailwind
- [x] Create backend for posting recipes
- [x] Create frontend for a recipe form
    - [x] Create cookbook component, just w/ background for now
    - [x] Create page components, just w/ background for now
    - [x] Create recipe form (with text values)
    - [x] Have recipe form submission submit the proper fetch request
        - [x] Add multer
        - [x] Make the image submission a file
        - [x] Handle errors
    - [x] Preview the image to upload
    - [x] Modify form based on length, meaning:
    - [x] Add a pages state to Cookbook to hold page data
    - [x] Add a currentPage state
    - [x] Update currentPage based on screenSize, including state toggle for margin for small screens *changed 'currentPage' to 'leftPage'
    - [x] Add a new recipe button
    - [x] Write pseudo-submit for future multi-page implementation
