### ISSUE TITLE
Feature #9: User can create a profile

### ISSUE THREAD

**Issue by TheDanYount** [TheDanYount/my-cookbook#10]
## ⚙️ Feature
User can create a profile
## 📐 Functionality
1. Lets users make an account
## ✅ Task List
- [x] Create backend for user creation
- [x] Create login homepage w/ create account link
- [x] Create new user form
- [x] Handle pseudo-form-submission
