### ISSUE TITLE
Feature #4: User can delete a recipe

### ISSUE THREAD

**Issue by TheDanYount** [TheDanYount/my-cookbook#5]
## ⚙️ Feature
User can delete recipes
## 📐 Functionality
1. The user can delete recipes in the Toc
## ✅ Task List
- [x] Create backend for deleting a recipe
- [x] On click of a delete (trash) button, open a portal for confirmation
- [x] Close the portal on click of a cancel button
- [x] Delete on confirmation
    - [x] In the database
    - [x] In the data model
        - [x] The recipe page itself
        - [x] The ToC entry
