### ISSUE TITLE
Feature #5: User can create a cookbook

### ISSUE THREAD

**Issue by TheDanYount** [TheDanYount/my-cookbook#6]
## ⚙️ Feature
User can create a cookbook
## 📐 Functionality
1. Start with user logged in, user has the option to create a cookbook
## ✅ Task List
- [x] Add fonts
- [x] Build frontend for menu/app drawer
- [x] Add transition for closing/opening the app drawer
- [x] Add useContext for cookbookId, use this for all instances of cookbookId
- [x] Write backend to create new cookbook
- [x] Create form for new cookbook
- [x] Handle form submission
