### ISSUE TITLE
Feature #6: User can read a cookbook

### ISSUE THREAD

**Issue by TheDanYount** [TheDanYount/my-cookbook#7]
## ⚙️ Feature
User can view a cookbook
## 📐 Functionality
1. On click of a cookbook in a user's carousel, a user is taken to that cookbook
2. Additionally, when user creates a cookbook, user is taken to that cookbook
## ✅ Task List
- [x] Write backend for getCookbooks
- [x] Handle loading, getting cookbooks when the user logs in
- [x] Add carousel functionality to menu
    - [x] New cookbook message changes from 'your first' to 'a new' w/ 1+ cookbook(s) (and cookbooks are displayed)
    - [x] Add media queries and display for 1, 2, 3 cookbooks
    - [x] Add smooth transition
- [x] Handle loading a cookbook on click
- [x] Handle loading a cookbook on creation of a cookbook
- [x] Fix Menu's open toggle
